---
title: "Análisis de la cobertura en medios digitales del tema: 'Narcotráfico'"
author:
- familyname: Castillo
  othernames: Diego F
  qualifications: Inteligencia Estratégica
- familyname: Castillo
  othernames: Claudio S
  qualifications: Investigación y Desarrollo
email: castilloclaudiosebastian@gmail.com
phone: (54) 9-11-26794601
department: Consulting
organization: Willow - Semantic Technology
number-sections: true
fig-height: 5
fig-width: 8
cite-method: biblatex
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1 # alternative 1.5
format: report-pdf
execute:
  echo: false
  warning: false
  message: false
---
```{python}
import sys
sys.path.append('../src')
from process import *
from database import *
from process import *
```

```{python}
#| tags: [parameters]
from datetime import date
start_date = "2023-08-28"
end_date = str(date.today())
topic = "narcotráfico"
```

```{python}
# Processing and consolidate news
collection_news = get_collection(host='mongodb://localhost:27017/', db_name='wdocuments', collection_name='news')
news = get_news(collection_news, start_date, end_date, topic, embed=False)
news = consolidate_news(news) # es muy importate consolidar pues la base en los primeros días tuvo duplicados
# Processing and consolidate ner
collection_newsner = get_collection(host='mongodb://localhost:27017/', db_name='wdocuments', collection_name='newsner')
newsner = get_ner_byindex(collection_newsner, news)
newsner = consolidate_ner(newsner)
# Tabla de Estadística por Provincia
newstat = get_news_stat(news, newsner)
# Tabla de noticas
table_news = table_news(news, type='abstract')
table_news.drop(columns=['autores', 'portal', 'link'], inplace=True)
# Tabla ner
table_ner = table_ner(newsner)
table_ner = table_ner.drop(columns=['varios'])
table_ner_personas = table_ner[['Ref.art','personas']]
table_ner_lugares = table_ner[['Ref.art','lugares']]
table_ner_organizaciones = table_ner[['Ref.art','organizaciones']]

```

# Intoducción

```{python, text.align = 'left'}
from IPython.display import display, Markdown
sd = start_date
ed = end_date
display(Markdown(
f"""
En este documento presentamos un análisis de la cobertura realizada sobre el tema **{topic}** entre los días {sd} y {ed}.  Los medios incluidos en nuestra base de seguimiento incluyen portales de noticias de todas las provincias, dando cobertura nacional al estudio. Dicho listado se puede ampliar o reconfigurar a demanda según necesidades particulares. 
"""
))
```

En lo que respecta a metodología empleamos *búsqueda semántica* y *algoritmos inteligentes* para el procesamiento de información. El resultado del documento debe brindar un conocimiento sistemático y actualizado del tópico en estudio bajo el **enfoque de los medios de comunicación**, con acceso a datos desagregados sobre eventos, personas, lugares y organizaciones asociadas al tema. En esta versión inicial de nuestro análisis nos concentramos en la presentación de los datos recuperados (ver: @tbl-news), dejando para próximos estudios la construcción de *modelos predictivos* y *proyecciones*. 

\newpage

# Estadística de noticias por provincia

```{python, text.align = 'left'}
from IPython.display import display, Markdown
t = topic
display(Markdown(
f"""
En esta tabla presentamos un listado ordenado de la cantidad de noticias recuperadas por provincia sobre el tema **{t}**.   
"""
))
```

Agregamos también la cantidad de entidades obtenidas en el *etiquetado* de los artículos, clasificadas como *personas* (@tbl-ner-personas), *lugares* (@tbl-ner-lugares), *organizaciones* (@tbl-ner-organizaciones). Otras entidades pueden extraerse bajo procesamientos específicos. Todas estas entidades permiten identificar y eventualmente recuperar entidades reiteradas en las noticias analizadas. Resaltamos que las entidades fueron clasificadas utilizando estrictamente sus características linguísticas, muchas de ellas con alto grado de certeza. Sin perjuicio de ello, para poder relacionar las entidades *liguísticamente* detectadas con entidades físicas es preciso cruzar los datos textuales con otras fuentes de datos que refuercen su validez. Tarea que reservamos para estudios particulares.   

```{python}
#| label: tbl-newstat
#| tbl-cap: Resumen_Extracción
Markdown(tabulate(
  newstat,
  headers=["provincia","cantidad_noticias", "personas", "lugares", "organizaciones", "varios"]
))

```


```{python}
#| label: graph-stat
#| fig-cap: "Cantidad de noticias por Provincia"

plot_dataframe(newstat, 
               x_col="cantidad_noticias", 
               y_col="provincia", 
               x_label="Cantidad de Noticias", 
               y_label="Provincias", 
               title="Cantidad de Noticias por Provincia")
```

\newpage

# Resumen de noticias por ubicación y fecha de publicación

La siguiente tabla presenta las noticias: su ubicación (generalmente provincia desde donde se publica), fecha, titular con el que se publicó en el portal y resumen del artículo (producido por nosotros). El número que aparece en la columna **Ref.Art** es el número de referencia para individualizar el artículo a lo largo de este documento (y en nuestra base de datos) y el **link** es el enlace al artículo del que se extrajo la información (si permanece en línea).

```{python}
#| label: tbl-news
#| tbl-cap: Noticias
Markdown(tabulate(
  table_news.reset_index(drop=True),
  headers=['Ref.Art.','Pcia/ot','fecha_art','titular','resumen', 'link'],  
  showindex=False,
  maxcolwidths=[1, 10, None, 15, 30, None],
))

```

# Extracción de personas por noticia

La próxima tabla muestra las entidades compatibles con **personas**. El número que aparece en la columna **Ref.Art** es el número de referencia para individualizar el artículo cuyo contendio detallamos en la tabla 2.   

```{python}
#| label: tbl-ner-personas
#| tbl-cap: Entidades-Personas
Markdown(tabulate(
  table_ner_personas.reset_index(drop=True),
  headers=['Ref.Art.','personas'],  
  showindex=False,
  maxcolwidths=[1, 80],
))
```

# Extracción de lugares por noticia

La próxima tabla muestra las entidades compatibles con **lugares**. El número que aparece en la columna **Ref.Art** es el número de referencia para individualizar el artículo cuyo contendio detallamos en la tabla 2.   

```{python}
#| label: tbl-ner-lugares
#| tbl-cap: Entidades-Lugares
Markdown(tabulate(
  table_ner_lugares.reset_index(drop=True),
  headers=['Ref.Art.','lugares'],  
  showindex=False,
  maxcolwidths=[1, 80],
))
```


# Extracción de organizaciones por noticia

La próxima tabla muestra las entidades compatibles con **organizaciones**. El número que aparece en la columna **Ref.Art** es el número de referencia para individualizar el artículo cuyo contendio detallamos en la tabla 2.   

```{python}
#| label: tbl-ner-organizaciones
#| tbl-cap: Entidades-Organizaciones
Markdown(tabulate(
  table_ner_organizaciones.reset_index(drop=True),
  headers=['Ref.Art.','organizaciones'],  
  showindex=False,
  maxcolwidths=[1, 80],
))
```

\newpage

# Gráficos

```{python}
#| label: graph-net-per
#| fig-cap: "Personas más nombradas"
df = ner_to_network(newsner)
fig = draw_top_ner(df, 20)
plt.show(fig)
```



<!-- In a famous paper, @BC64 introduced a family of transformations \dots -->
